# Generated by Django 3.0.8 on 2020-07-17 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_event_environment'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='address',
            field=models.GenericIPAddressField(default='191.177.182.188'),
            preserve_default=False,
        ),
    ]
