# Generated by Django 3.0.8 on 2020-07-17 22:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_event_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='address',
            field=models.GenericIPAddressField(validators=[django.core.validators.validate_ipv4_address]),
        ),
    ]
