# Generated by Django 3.0.8 on 2020-07-18 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_event_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='events',
            field=models.IntegerField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
