language: python
python:
  - "3.8.3"

stages:
  - name: test
  - name: deploy

jobs:
  include:
  - stage: test
    name: Unit Test
    script: python manage.py test
  - stage: deploy
    name: Heroku Deploy
    script: /bin/true
    deploy:
      provider: heroku
      api_key:
        secure: PwLw88CflOaUWDI+oQ0JulyJHtrkRSdQhnI39xti12uToJ0xfGIUB1KIZmlbGJtB90ble4pUEYbq4/pmsTUu+gCjNO/4rerQnC49vW8hK0XYjZHrYARUmx3vReg/t1hsBN7y5kDzb4IkR2ScIngGwg2pUqgaYwC7kqDl5qDluPzK43EijnrR7ZnNYgmqYiChXzOiYLUPlrH+09cl87cB10/iOsvxOxcXx+6nNhlBPSvCr1dewvRhQnwqyrkQn5GxaAKYgsSxGOtE0DqYDvojhNwZ5Vhd+UUC5OncJYw2WGBKVebHG+kslEnrkYS4UlgE33Szv26F+p9GLZuoftTrazL0NBUimG9JkqpeGA4FeQFmZLqG6WF/EmG2tZzMPZ6mVdE5nLceywjLNqemohteKJwXAfPjPw0kvsZroh/tnTyJ4Dcn+8j3sCVlyn23THJ5LB39y9M7oJkYnP6CSjWxBX9k61uD3T4XkTsLRqe8NLwo6SIBT2qkaMhi13QPymeI8gGnOxOCLPiBZo6In2xnsClBdnBMOZok+op2yripVp1ZYuSdnaVaidotxJgwfGhgjsCOo7k2aCLBp5JqrKyXi/hdzlT6U8ksrlj6Zd0Tt4rsbP8KhoQYHhvazRInTpt2RUhFruO4EThBqw4aPzXUl3+OPAgfHY44cr+PGGPQrAA=
      skip_cleanup: true
      app: projeto-centraldeerros
      on:
        branch: master

      run: "python manage.py migrate"

